export const apiCategories = [
  {
    id: '1',
    name: '用户相关',
    parentId: '0',
    sort: 1,
    type: 1,
    typeName: '用户',
    fields: [],
    amount: 8,
    apiAmount: 0,
    childAmount: 40,
    childApiAmount: 35,
    createAt: '2023-01-01T00:00:00Z',
    updateAt: '2023-06-01T00:00:00Z',
    udp: {},
    classifications: [
      { 
        id: '1-1',
        name: '用户信息', 
        parentId: '1',
        sort: 1,
        type: 1,
        typeName: '信息',
        fields: [],
        amount: 10,
        apiAmount: 3,
        childAmount: 12,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '1-1-1', 
            name: '用户资料',
            parentId: '1-1',
            sort: 1,
            type: 2,
            typeName: '基础',
            fields: [],
            amount: 0,
            apiAmount: 2,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '1-1-2', 
            name: '用户设置',
            parentId: '1-1',
            sort: 2,
            type: 2,
            typeName: '基础',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '1-1-3', 
            name: '安全信息',
            parentId: '1-1',
            sort: 3,
            type: 2,
            typeName: '安全',
            fields: [],
            amount: 12,
            apiAmount: 0,
            childAmount: 12,
            childApiAmount: 10,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: [
              { 
                id: '1-1-3-1', 
                name: '登录记录',
                parentId: '1-1-3',
                sort: 1,
                type: 3,
                typeName: '记录',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '1-1-3-2', 
                name: '安全设置',
                parentId: '1-1-3',
                sort: 2,
                type: 3,
                typeName: '设置',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '1-1-3-3', 
                name: '密码管理',
                parentId: '1-1-3',
                sort: 3,
                type: 3,
                typeName: '管理',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '1-1-3-4', 
                name: '二次验证',
                parentId: '1-1-3',
                sort: 4,
                type: 3,
                typeName: '验证',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '1-1-3-5', 
                name: '设备管理',
                parentId: '1-1-3',
                sort: 5,
                type: 3,
                typeName: '管理',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              }
            ]
          },
          { 
            id: '1-1-4', 
            name: '头像管理',
            parentId: '1-1',
            sort: 4,
            type: 2,
            typeName: '基础',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '1-1-5', 
            name: '兴趣标签',
            parentId: '1-1',
            sort: 5,
            type: 2,
            typeName: '基础',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { value: '1-1-6', label: '隐私设置' },
          { value: '1-1-7', label: '个性化' },
          { value: '1-1-8', label: '账号绑定' },
          { value: '1-1-9', label: '职业信息' },
          { value: '1-1-10', label: '联系方式' }
        ]
      },
      { 
        id: '1-2',
        name: '用户认证',
        parentId: '1',
        sort: 2,
        type: 1,
        typeName: '认证',
        fields: [],
        amount: 15,
        apiAmount: 5,
        childAmount: 15,
        childApiAmount: 12,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '1-2-1', 
            name: '登录',
            parentId: '1-2',
            sort: 1,
            type: 2,
            typeName: '基础',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '1-2-2', 
            name: '注册',
            parentId: '1-2',
            sort: 2,
            type: 2,
            typeName: '基础',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '1-2-3', 
            name: '找回密码',
            parentId: '1-2',
            sort: 3,
            type: 2,
            typeName: '基础',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { value: '1-2-4', label: '短信验证' },
          { value: '1-2-5', label: '邮箱验证' },
          { value: '1-2-6', label: '人脸识别' },
          { value: '1-2-7', label: '指纹识别' },
          { value: '1-2-8', label: 'OAuth认证' },
          { value: '1-2-9', label: 'SSO登录' },
          { value: '1-2-10', label: '扫码登录' },
          { value: '1-2-11', label: '一键登录' },
          { value: '1-2-12', label: '安全问题验证' },
          { value: '1-2-13', label: 'TOTP验证' },
          { value: '1-2-14', label: '实名认证' },
          { value: '1-2-15', label: '企业认证' }
        ]
      },
      { 
        id: '1-3',
        name: '用户关系',
        parentId: '1',
        sort: 3,
        type: 1,
        typeName: '关系',
        fields: [],
        amount: 8,
        apiAmount: 2,
        childAmount: 8,
        childApiAmount: 8,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '1-3-1', 
            name: '好友管理',
            parentId: '1-3',
            sort: 1,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '1-3-2', 
            name: '分组管理',
            parentId: '1-3',
            sort: 2,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { value: '1-3-3', label: '黑名单' },
          { value: '1-3-4', label: '关注/粉丝' },
          { value: '1-3-5', label: '标签管理' },
          { value: '1-3-6', label: '互动记录' },
          { value: '1-3-7', label: '推荐好友' },
          { value: '1-3-8', label: '共同好友' }
        ]
      },
      { 
        id: '1-4', 
        name: '通知设置',
        parentId: '1',
        sort: 4,
        type: 1,
        typeName: '设置',
        fields: [],
        amount: 0,
        apiAmount: 1,
        childAmount: 0,
        childApiAmount: 0,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: []
      },
      { value: '1-5', label: '账号状态' },
      { value: '1-6', label: '用户等级' },
      { value: '1-7', label: '积分管理' },
      { value: '1-8', label: '会员权益' }
    ],
  },
  {
    id: '2',
    name: '订单相关',
    parentId: '0',
    sort: 2,
    type: 1,
    typeName: '订单',
    fields: [],
    amount: 4,
    apiAmount: 0,
    childAmount: 55,
    childApiAmount: 48,
    createAt: '2023-01-01T00:00:00Z',
    updateAt: '2023-06-01T00:00:00Z',
    udp: {},
    classifications: [
      { 
        id: '2-1',
        name: '订单管理',
        parentId: '2',
        sort: 1,
        type: 1,
        typeName: '管理',
        fields: [],
        amount: 15,
        apiAmount: 5,
        childAmount: 15,
        childApiAmount: 15,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '2-1-1', 
            name: '创建订单',
            parentId: '2-1',
            sort: 1,
            type: 2,
            typeName: '操作',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-1-2', 
            name: '查询订单',
            parentId: '2-1',
            sort: 2,
            type: 2,
            typeName: '查询',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-1-3', 
            name: '取消订单',
            parentId: '2-1',
            sort: 3,
            type: 2,
            typeName: '操作',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { value: '2-1-4', label: '订单详情' },
          { value: '2-1-5', label: '订单评价' },
          { value: '2-1-6', label: '订单跟踪' },
          { value: '2-1-7', label: '批量操作' },
          { value: '2-1-8', label: '订单导出' },
          { value: '2-1-9', label: '订单备注' },
          { value: '2-1-10', label: '订单打印' },
          { value: '2-1-11', label: '订单审核' },
          { value: '2-1-12', label: '订单分配' },
          { value: '2-1-13', label: '订单合并' },
          { value: '2-1-14', label: '订单拆分' },
          { value: '2-1-15', label: '订单归档' }
        ]
      },
      {
        id: '2-2',
        name: '订单状态',
        parentId: '2',
        sort: 2,
        type: 1,
        typeName: '状态',
        fields: [],
        amount: 18,
        apiAmount: 3,
        childAmount: 18,
        childApiAmount: 18,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '2-2-1', 
            name: '待付款',
            parentId: '2-2',
            sort: 1,
            type: 2,
            typeName: '状态',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-2-2', 
            name: '已付款',
            parentId: '2-2',
            sort: 2,
            type: 2,
            typeName: '状态',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-2-3', 
            name: '配送中',
            parentId: '2-2',
            sort: 3,
            type: 2,
            typeName: '状态',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { value: '2-2-4', label: '已完成' },
          { value: '2-2-5', label: '已取消' },
          { value: '2-2-6', label: '已退款' },
          { value: '2-2-7', label: '部分退款' },
          { value: '2-2-8', label: '退款中' },
          { value: '2-2-9', label: '待评价' },
          { value: '2-2-10', label: '已关闭' },
          { value: '2-2-11', label: '待发货' },
          { value: '2-2-12', label: '已发货' },
          { value: '2-2-13', label: '待收货' },
          { value: '2-2-14', label: '异常订单' },
          { value: '2-2-15', label: '售后中' },
          { value: '2-2-16', label: '挂起中' },
          { value: '2-2-17', label: '预订单' },
          { value: '2-2-18', label: '待审核' }
        ],
      },
      {
        id: '2-3',
        name: '支付管理',
        parentId: '2',
        sort: 3,
        type: 1,
        typeName: '支付',
        fields: [],
        amount: 10,
        apiAmount: 2,
        childAmount: 10,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '2-3-1', 
            name: '支付方式',
            parentId: '2-3',
            sort: 1,
            type: 2,
            typeName: '支付',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-3-2', 
            name: '退款管理',
            parentId: '2-3',
            sort: 2,
            type: 2,
            typeName: '退款',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-3-3', 
            name: '发票管理',
            parentId: '2-3',
            sort: 3,
            type: 1,
            typeName: '发票',
            fields: [],
            amount: 4,
            apiAmount: 1,
            childAmount: 4,
            childApiAmount: 4,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: [
              { 
                id: '2-3-3-1', 
                name: '申请发票',
                parentId: '2-3-3',
                sort: 1,
                type: 2,
                typeName: '操作',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-2', 
                name: '发票记录',
                parentId: '2-3-3',
                sort: 2,
                type: 2,
                typeName: '记录',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-3', 
                name: '发票模板',
                parentId: '2-3-3',
                sort: 3,
                type: 2,
                typeName: '模板',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-4', 
                name: '发票抬头',
                parentId: '2-3-3',
                sort: 4,
                type: 2,
                typeName: '基础',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-5', 
                name: '电子发票',
                parentId: '2-3-3',
                sort: 5,
                type: 2,
                typeName: '电子',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-6', 
                name: '纸质发票',
                parentId: '2-3-3',
                sort: 6,
                type: 2,
                typeName: '纸质',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-7', 
                name: '增值税发票',
                parentId: '2-3-3',
                sort: 7,
                type: 2,
                typeName: '增值税',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-8', 
                name: '发票验真',
                parentId: '2-3-3',
                sort: 8,
                type: 2,
                typeName: '验证',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-9', 
                name: '发票邮寄',
                parentId: '2-3-3',
                sort: 9,
                type: 2,
                typeName: '邮寄',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '2-3-3-10', 
                name: '发票打印',
                parentId: '2-3-3',
                sort: 10,
                type: 2,
                typeName: '打印',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              }
            ]
          },
          { value: '2-3-4', label: '支付配置' },
          { value: '2-3-5', label: '支付记录' },
          { value: '2-3-6', label: '支付回调' },
          { value: '2-3-7', label: '支付验证' },
          { value: '2-3-8', label: '定金管理' },
          { value: '2-3-9', label: '余额支付' },
          { value: '2-3-10', label: '积分抵扣' }
        ]
      },
      {
        id: '2-4',
        name: '售后服务',
        parentId: '2',
        sort: 4,
        type: 1,
        typeName: '售后',
        fields: [],
        amount: 8,
        apiAmount: 2,
        childAmount: 8,
        childApiAmount: 8,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '2-4-1', 
            name: '退货申请',
            parentId: '2-4',
            sort: 1,
            type: 2,
            typeName: '申请',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-4-2', 
            name: '换货申请',
            parentId: '2-4',
            sort: 2,
            type: 2,
            typeName: '申请',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-4-3', 
            name: '维修申请',
            parentId: '2-4',
            sort: 3,
            type: 2,
            typeName: '申请',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-4-4', 
            name: '售后跟踪',
            parentId: '2-4',
            sort: 4,
            type: 2,
            typeName: '跟踪',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-4-5', 
            name: '投诉管理',
            parentId: '2-4',
            sort: 5,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-4-6', 
            name: '售后评价',
            parentId: '2-4',
            sort: 6,
            type: 2,
            typeName: '评价',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-4-7', 
            name: '问题归类',
            parentId: '2-4',
            sort: 7,
            type: 2,
            typeName: '归类',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '2-4-8', 
            name: '赔偿处理',
            parentId: '2-4',
            sort: 8,
            type: 2,
            typeName: '处理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      },
    ],
  },
  {
    id: '3',
    name: '产品相关',
    parentId: '0',
    sort: 3,
    type: 1,
    typeName: '产品',
    fields: [],
    amount: 5,
    apiAmount: 1,
    childAmount: 45,
    childApiAmount: 39,
    createAt: '2023-01-01T00:00:00Z',
    updateAt: '2023-06-01T00:00:00Z',
    udp: {},
    classifications: [
      { 
        id: '3-1', 
        name: '产品列表',
        parentId: '3',
        sort: 1,
        type: 1,
        typeName: '列表',
        fields: [],
        amount: 0,
        apiAmount: 1,
        childAmount: 0,
        childApiAmount: 0,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: []
      },
      { 
        id: '3-2',
        name: '产品详情',
        parentId: '3',
        sort: 2,
        type: 1,
        typeName: '详情',
        fields: [],
        amount: 20,
        apiAmount: 3,
        childAmount: 20,
        childApiAmount: 18,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '3-2-1', 
            name: '基本信息',
            parentId: '3-2',
            sort: 1,
            type: 2,
            typeName: '信息',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-2-2', 
            name: '规格参数',
            parentId: '3-2',
            sort: 2,
            type: 2,
            typeName: '参数',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-2-3', 
            name: '价格库存',
            parentId: '3-2',
            sort: 3,
            type: 2,
            typeName: '价格',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { value: '3-2-4', label: '产品图片' },
          { value: '3-2-5', label: '产品视频' },
          { value: '3-2-6', label: '产品描述' },
          { value: '3-2-7', label: '相关产品' },
          { value: '3-2-8', label: '产品评价' },
          { value: '3-2-9', label: '产品标签' },
          { value: '3-2-10', label: '产品属性' },
          { value: '3-2-11', label: '上下架状态' },
          { value: '3-2-12', label: '销售记录' },
          { value: '3-2-13', label: '产品组合' },
          { value: '3-2-14', label: '产品配件' },
          { value: '3-2-15', label: '产品说明书' },
          { value: '3-2-16', label: '产品保修' },
          { value: '3-2-17', label: '产品认证' },
          { value: '3-2-18', label: '产品FAQ' },
          { value: '3-2-19', label: '供应商信息' },
          { value: '3-2-20', label: '产品包装' }
        ]
      },
      { 
        id: '3-3',
        name: '产品分类',
        parentId: '3',
        sort: 3,
        type: 1,
        typeName: '分类',
        fields: [],
        amount: 10,
        apiAmount: 2,
        childAmount: 10,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '3-3-1', 
            name: '一级分类',
            parentId: '3-3',
            sort: 1,
            type: 2,
            typeName: '分类',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-3-2', 
            name: '二级分类',
            parentId: '3-3',
            sort: 2,
            type: 2,
            typeName: '分类',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { value: '3-3-3', label: '三级分类' },
          { value: '3-3-4', label: '分类管理' },
          { value: '3-3-5', label: '分类属性' },
          { value: '3-3-6', label: '分类统计' },
          { value: '3-3-7', label: '分类导航' },
          { value: '3-3-8', label: '分类模板' },
          { value: '3-3-9', label: '分类图标' },
          { value: '3-3-10', label: '分类推荐' }
        ]
      },
      {
        id: '3-4',
        name: '品牌管理',
        parentId: '3',
        sort: 4,
        type: 1,
        typeName: '品牌',
        fields: [],
        amount: 8,
        apiAmount: 2,
        childAmount: 8,
        childApiAmount: 8,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '3-4-1', 
            name: '品牌列表',
            parentId: '3-4',
            sort: 1,
            type: 2,
            typeName: '列表',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-4-2', 
            name: '品牌详情',
            parentId: '3-4',
            sort: 2,
            type: 2,
            typeName: '详情',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { value: '3-4-3', label: '品牌分类' },
          { value: '3-4-4', label: '品牌授权' },
          { value: '3-4-5', label: '品牌推荐' },
          { value: '3-4-6', label: '品牌活动' },
          { value: '3-4-7', label: '品牌故事' },
          { value: '3-4-8', label: '品牌认证' }
        ]
      },
      {
        id: '3-5',
        name: '库存管理',
        parentId: '3',
        sort: 5,
        type: 1,
        typeName: '库存',
        fields: [],
        amount: 10,
        apiAmount: 2,
        childAmount: 10,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '3-5-1', 
            name: '库存查询',
            parentId: '3-5',
            sort: 1,
            type: 2,
            typeName: '查询',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-2', 
            name: '入库管理',
            parentId: '3-5',
            sort: 2,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-3', 
            name: '出库管理',
            parentId: '3-5',
            sort: 3,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-4', 
            name: '库存预警',
            parentId: '3-5',
            sort: 4,
            type: 2,
            typeName: '预警',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-5', 
            name: '库存盘点',
            parentId: '3-5',
            sort: 5,
            type: 2,
            typeName: '盘点',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-6', 
            name: '库存调拨',
            parentId: '3-5',
            sort: 6,
            type: 2,
            typeName: '调拨',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-7', 
            name: '批次管理',
            parentId: '3-5',
            sort: 7,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-8', 
            name: '库位管理',
            parentId: '3-5',
            sort: 8,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-9', 
            name: '仓库管理',
            parentId: '3-5',
            sort: 9,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-10', 
            name: '库存日志',
            parentId: '3-5',
            sort: 10,
            type: 2,
            typeName: '日志',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-11', 
            name: '库存报表',
            parentId: '3-5',
            sort: 11,
            type: 2,
            typeName: '报表',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '3-5-12', 
            name: '库存预测',
            parentId: '3-5',
            sort: 12,
            type: 2,
            typeName: '预测',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      },
    ],
  },
  {
    id: '4',
    name: '系统相关',
    parentId: '0',
    sort: 4,
    type: 1,
    typeName: '系统',
    fields: [],
    amount: 10,
    apiAmount: 2,
    childAmount: 40,
    childApiAmount: 38,
    createAt: '2023-01-01T00:00:00Z',
    updateAt: '2023-06-01T00:00:00Z',
    udp: {},
    classifications: [
      { 
        id: '4-1',
        name: '系统设置',
        parentId: '4',
        sort: 1,
        type: 1,
        typeName: '设置',
        fields: [],
        amount: 10,
        apiAmount: 2,
        childAmount: 10,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '4-1-1', 
            name: '基础设置',
            parentId: '4-1',
            sort: 1,
            type: 2,
            typeName: '基础',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-2', 
            name: '安全设置',
            parentId: '4-1',
            sort: 2,
            type: 2,
            typeName: '安全',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-3', 
            name: '权限设置',
            parentId: '4-1',
            sort: 3,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-4', 
            name: '界面设置',
            parentId: '4-1',
            sort: 4,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-5', 
            name: '通知设置',
            parentId: '4-1',
            sort: 5,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-6', 
            name: '性能优化',
            parentId: '4-1',
            sort: 6,
            type: 2,
            typeName: '优化',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-7', 
            name: '集成配置',
            parentId: '4-1',
            sort: 7,
            type: 2,
            typeName: '配置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-8', 
            name: '多语言设置',
            parentId: '4-1',
            sort: 8,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-9', 
            name: '时区设置',
            parentId: '4-1',
            sort: 9,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-10', 
            name: '字体设置',
            parentId: '4-1',
            sort: 10,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-11', 
            name: '默认值',
            parentId: '4-1',
            sort: 11,
            type: 2,
            typeName: '默认',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-12', 
            name: '单位设置',
            parentId: '4-1',
            sort: 12,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-13', 
            name: '货币设置',
            parentId: '4-1',
            sort: 13,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-14', 
            name: '税率设置',
            parentId: '4-1',
            sort: 14,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-15', 
            name: '工作流设置',
            parentId: '4-1',
            sort: 15,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-16', 
            name: '备份策略',
            parentId: '4-1',
            sort: 16,
            type: 2,
            typeName: '策略',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-17', 
            name: '计划任务',
            parentId: '4-1',
            sort: 17,
            type: 2,
            typeName: '任务',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-18', 
            name: '插件管理',
            parentId: '4-1',
            sort: 18,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-19', 
            name: '主题管理',
            parentId: '4-1',
            sort: 19,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-20', 
            name: '菜单管理',
            parentId: '4-1',
            sort: 20,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-21', 
            name: '导入导出',
            parentId: '4-1',
            sort: 21,
            type: 2,
            typeName: '导入',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-22', 
            name: '水印设置',
            parentId: '4-1',
            sort: 22,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-23', 
            name: '数据字典',
            parentId: '4-1',
            sort: 23,
            type: 2,
            typeName: '字典',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-24', 
            name: '系统升级',
            parentId: '4-1',
            sort: 24,
            type: 2,
            typeName: '升级',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-1-25', 
            name: '白名单设置',
            parentId: '4-1',
            sort: 25,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      },
      { 
        id: '4-2',
        name: '日志管理',
        parentId: '4',
        sort: 2,
        type: 1,
        typeName: '日志',
        fields: [],
        amount: 10,
        apiAmount: 2,
        childAmount: 10,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '4-2-1', 
            name: '操作日志',
            parentId: '4-2',
            sort: 1,
            type: 2,
            typeName: '日志',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-2', 
            name: '登录日志',
            parentId: '4-2',
            sort: 2,
            type: 2,
            typeName: '日志',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-3', 
            name: '异常日志',
            parentId: '4-2',
            sort: 3,
            type: 2,
            typeName: '日志',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-4', 
            name: '系统日志',
            parentId: '4-2',
            sort: 4,
            type: 2,
            typeName: '日志',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-5', 
            name: '审计日志',
            parentId: '4-2',
            sort: 5,
            type: 2,
            typeName: '日志',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-6', 
            name: '安全日志',
            parentId: '4-2',
            sort: 6,
            type: 2,
            typeName: '日志',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-7', 
            name: '性能日志',
            parentId: '4-2',
            sort: 7,
            type: 2,
            typeName: '日志',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-8', 
            name: '日志搜索',
            parentId: '4-2',
            sort: 8,
            type: 2,
            typeName: '搜索',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-9', 
            name: '日志分析',
            parentId: '4-2',
            sort: 9,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-10', 
            name: '日志导出',
            parentId: '4-2',
            sort: 10,
            type: 2,
            typeName: '导出',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-11', 
            name: '日志归档',
            parentId: '4-2',
            sort: 11,
            type: 2,
            typeName: '归档',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-2-12', 
            name: '日志清理',
            parentId: '4-2',
            sort: 12,
            type: 2,
            typeName: '清理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      },
      { 
        id: '4-3',
        name: '数据维护',
        parentId: '4',
        sort: 3,
        type: 1,
        typeName: '数据',
        fields: [],
        amount: 10,
        apiAmount: 2,
        childAmount: 10,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '4-3-1', 
            name: '数据备份',
            parentId: '4-3',
            sort: 1,
            type: 2,
            typeName: '备份',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-3-2', 
            name: '数据恢复',
            parentId: '4-3',
            sort: 2,
            type: 2,
            typeName: '恢复',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-3-3', 
            name: '缓存管理',
            parentId: '4-3',
            sort: 3,
            type: 1,
            typeName: '缓存',
            fields: [],
            amount: 4,
            apiAmount: 1,
            childAmount: 4,
            childApiAmount: 4,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: [
              { 
                id: '4-3-3-1', 
                name: '清除缓存',
                parentId: '4-3-3',
                sort: 1,
                type: 2,
                typeName: '清除',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-2', 
                name: '缓存设置',
                parentId: '4-3-3',
                sort: 2,
                type: 2,
                typeName: '设置',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-3', 
                name: '缓存统计',
                parentId: '4-3-3',
                sort: 3,
                type: 2,
                typeName: '统计',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-4', 
                name: '缓存预热',
                parentId: '4-3-3',
                sort: 4,
                type: 2,
                typeName: '预热',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-5', 
                name: '缓存策略',
                parentId: '4-3-3',
                sort: 5,
                type: 2,
                typeName: '策略',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-6', 
                name: '缓存监控',
                parentId: '4-3-3',
                sort: 6,
                type: 2,
                typeName: '监控',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-7', 
                name: '缓存分析',
                parentId: '4-3-3',
                sort: 7,
                type: 2,
                typeName: '分析',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-8', 
                name: '分布式缓存',
                parentId: '4-3-3',
                sort: 8,
                type: 2,
                typeName: '缓存',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-9', 
                name: '本地缓存',
                parentId: '4-3-3',
                sort: 9,
                type: 2,
                typeName: '缓存',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-10', 
                name: '缓存同步',
                parentId: '4-3-3',
                sort: 10,
                type: 2,
                typeName: '同步',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-11', 
                name: '缓存穿透防护',
                parentId: '4-3-3',
                sort: 11,
                type: 2,
                typeName: '防护',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-12', 
                name: '缓存雪崩防护',
                parentId: '4-3-3',
                sort: 12,
                type: 2,
                typeName: '防护',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-13', 
                name: '缓存击穿防护',
                parentId: '4-3-3',
                sort: 13,
                type: 2,
                typeName: '防护',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-14', 
                name: '热点数据缓存',
                parentId: '4-3-3',
                sort: 14,
                type: 2,
                typeName: '缓存',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              },
              { 
                id: '4-3-3-15', 
                name: '缓存过期策略',
                parentId: '4-3-3',
                sort: 15,
                type: 2,
                typeName: '策略',
                fields: [],
                amount: 0,
                apiAmount: 1,
                childAmount: 0,
                childApiAmount: 0,
                createAt: '2023-01-01T00:00:00Z',
                updateAt: '2023-06-01T00:00:00Z',
                udp: {},
                classifications: []
              }
            ]
          },
          { value: '4-3-4', label: '数据压缩' },
          { value: '4-3-5', label: '数据迁移' },
          { value: '4-3-6', label: '数据校验' },
          { value: '4-3-7', label: '数据修复' },
          { value: '4-3-8', label: '数据清理' },
          { value: '4-3-9', label: '数据同步' },
          { value: '4-3-10', label: '数据脱敏' }
        ]
      },
      {
        id: '4-4',
        name: '用户权限',
        parentId: '4',
        sort: 4,
        type: 1,
        typeName: '权限',
        fields: [],
        amount: 10,
        apiAmount: 2,
        childAmount: 10,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '4-4-1', 
            name: '角色管理',
            parentId: '4-4',
            sort: 1,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-2', 
            name: '权限分配',
            parentId: '4-4',
            sort: 2,
            type: 2,
            typeName: '分配',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-3', 
            name: '菜单权限',
            parentId: '4-4',
            sort: 3,
            type: 2,
            typeName: '权限',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-4', 
            name: '数据权限',
            parentId: '4-4',
            sort: 4,
            type: 2,
            typeName: '权限',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-5', 
            name: '部门管理',
            parentId: '4-4',
            sort: 5,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-6', 
            name: '岗位管理',
            parentId: '4-4',
            sort: 6,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-7', 
            name: '用户组管理',
            parentId: '4-4',
            sort: 7,
            type: 2,
            typeName: '管理',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-8', 
            name: '权限模板',
            parentId: '4-4',
            sort: 8,
            type: 2,
            typeName: '模板',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-9', 
            name: '权限审计',
            parentId: '4-4',
            sort: 9,
            type: 2,
            typeName: '审计',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-10', 
            name: '权限申请',
            parentId: '4-4',
            sort: 10,
            type: 2,
            typeName: '申请',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-11', 
            name: '权限委托',
            parentId: '4-4',
            sort: 11,
            type: 2,
            typeName: '委托',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-12', 
            name: '权限继承',
            parentId: '4-4',
            sort: 12,
            type: 2,
            typeName: '继承',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-13', 
            name: '多租户权限',
            parentId: '4-4',
            sort: 13,
            type: 2,
            typeName: '权限',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-14', 
            name: '动态权限',
            parentId: '4-4',
            sort: 14,
            type: 2,
            typeName: '权限',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-4-15', 
            name: '临时权限',
            parentId: '4-4',
            sort: 15,
            type: 2,
            typeName: '权限',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      },
      {
        id: '4-5',
        name: '消息通知',
        parentId: '4',
        sort: 5,
        type: 1,
        typeName: '消息',
        fields: [],
        amount: 10,
        apiAmount: 2,
        childAmount: 10,
        childApiAmount: 10,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '4-5-1', 
            name: '消息模板',
            parentId: '4-5',
            sort: 1,
            type: 2,
            typeName: '模板',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-2', 
            name: '站内通知',
            parentId: '4-5',
            sort: 2,
            type: 2,
            typeName: '通知',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-3', 
            name: '短信通知',
            parentId: '4-5',
            sort: 3,
            type: 2,
            typeName: '通知',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-4', 
            name: '邮件通知',
            parentId: '4-5',
            sort: 4,
            type: 2,
            typeName: '通知',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-5', 
            name: '推送通知',
            parentId: '4-5',
            sort: 5,
            type: 2,
            typeName: '通知',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-6', 
            name: '消息队列',
            parentId: '4-5',
            sort: 6,
            type: 2,
            typeName: '队列',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-7', 
            name: '消息中心',
            parentId: '4-5',
            sort: 7,
            type: 2,
            typeName: '中心',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-8', 
            name: '消息统计',
            parentId: '4-5',
            sort: 8,
            type: 2,
            typeName: '统计',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-9', 
            name: '通知设置',
            parentId: '4-5',
            sort: 9,
            type: 2,
            typeName: '设置',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '4-5-10', 
            name: '未读消息',
            parentId: '4-5',
            sort: 10,
            type: 2,
            typeName: '消息',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      },
    ],
  },
  {
    id: '5',
    name: '数据分析',
    parentId: '0',
    sort: 5,
    type: 1,
    typeName: '数据',
    fields: [],
    amount: 3,
    apiAmount: 1,
    childAmount: 3,
    childApiAmount: 3,
    createAt: '2023-01-01T00:00:00Z',
    updateAt: '2023-06-01T00:00:00Z',
    udp: {},
    classifications: [
      {
        id: '5-1',
        name: '数据报表',
        parentId: '5',
        sort: 1,
        type: 1,
        typeName: '报表',
        fields: [],
        amount: 3,
        apiAmount: 1,
        childAmount: 3,
        childApiAmount: 3,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '5-1-1', 
            name: '销售报表',
            parentId: '5-1',
            sort: 1,
            type: 2,
            typeName: '报表',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-1-2', 
            name: '用户报表',
            parentId: '5-1',
            sort: 2,
            type: 2,
            typeName: '报表',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-1-3', 
            name: '产品报表',
            parentId: '5-1',
            sort: 3,
            type: 2,
            typeName: '报表',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      },
      {
        id: '5-2',
        name: '数据可视化',
        parentId: '5',
        sort: 2,
        type: 1,
        typeName: '可视化',
        fields: [],
        amount: 3,
        apiAmount: 1,
        childAmount: 3,
        childApiAmount: 3,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '5-2-1', 
            name: '实时数据',
            parentId: '5-2',
            sort: 1,
            type: 2,
            typeName: '数据',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-2', 
            name: '数据大屏',
            parentId: '5-2',
            sort: 2,
            type: 2,
            typeName: '大屏',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-3', 
            name: '趋势图表',
            parentId: '5-2',
            sort: 3,
            type: 2,
            typeName: '图表',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-4', 
            name: '对比分析',
            parentId: '5-2',
            sort: 4,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-5', 
            name: '热力图',
            parentId: '5-2',
            sort: 5,
            type: 2,
            typeName: '图表',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-6', 
            name: '地理分布',
            parentId: '5-2',
            sort: 6,
            type: 2,
            typeName: '分布',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-7', 
            name: '漏斗分析',
            parentId: '5-2',
            sort: 7,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-8', 
            name: '用户路径',
            parentId: '5-2',
            sort: 8,
            type: 2,
            typeName: '路径',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-9', 
            name: '自定义看板',
            parentId: '5-2',
            sort: 9,
            type: 2,
            typeName: '看板',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-2-10', 
            name: '指标监控',
            parentId: '5-2',
            sort: 10,
            type: 2,
            typeName: '监控',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      },
      {
        id: '5-3',
        name: '业务分析',
        parentId: '5',
        sort: 3,
        type: 1,
        typeName: '分析',
        fields: [],
        amount: 3,
        apiAmount: 1,
        childAmount: 3,
        childApiAmount: 3,
        createAt: '2023-01-01T00:00:00Z',
        updateAt: '2023-06-01T00:00:00Z',
        udp: {},
        classifications: [
          { 
            id: '5-3-1', 
            name: '用户分析',
            parentId: '5-3',
            sort: 1,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-2', 
            name: '产品分析',
            parentId: '5-3',
            sort: 2,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-3', 
            name: '渠道分析',
            parentId: '5-3',
            sort: 3,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-4', 
            name: '转化分析',
            parentId: '5-3',
            sort: 4,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-5', 
            name: '留存分析',
            parentId: '5-3',
            sort: 5,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-6', 
            name: '活跃分析',
            parentId: '5-3',
            sort: 6,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-7', 
            name: '行为分析',
            parentId: '5-3',
            sort: 7,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-8', 
            name: '归因分析',
            parentId: '5-3',
            sort: 8,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-9', 
            name: '分群分析',
            parentId: '5-3',
            sort: 9,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-10', 
            name: '竞品分析',
            parentId: '5-3',
            sort: 10,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-11', 
            name: '预测分析',
            parentId: '5-3',
            sort: 11,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          },
          { 
            id: '5-3-12', 
            name: 'ROI分析',
            parentId: '5-3',
            sort: 12,
            type: 2,
            typeName: '分析',
            fields: [],
            amount: 0,
            apiAmount: 1,
            childAmount: 0,
            childApiAmount: 0,
            createAt: '2023-01-01T00:00:00Z',
            updateAt: '2023-06-01T00:00:00Z',
            udp: {},
            classifications: []
          }
        ]
      }
    ]
  }
];

export default apiCategories; 