// 市场配置文件 - 定义每个市场支持的模块和功能

// 模块列表
export const MODULES = {
  API_MANAGEMENT: 'apiManagement',
  DATASET_MANAGEMENT: 'datasetManagement', 
  LOWCODE_BUILDER: 'lowcodeBuilder',
  REVIEW_ORDERS: 'reviewOrders',
  ANALYTICS: 'analytics',
  ADMIN: 'admin'
};

// 特性列表 - 按模块组织
export const FEATURES = {
  [MODULES.API_MANAGEMENT]: {
    CREATE_API: 'createApi',
    API_VERSIONING: 'apiVersioning',
    API_DOCUMENTATION: 'apiDocumentation',
    API_MOCKING: 'apiMocking',
    API_TESTING: 'apiTesting',
    API_STATISTICS: 'apiStatistics',
    API_PERFORMANCE: 'apiPerformance',
    API_USAGE_ANALYTICS: 'apiUsageAnalytics',
    API_ERROR_ANALYTICS: 'apiErrorAnalytics',
    API_COUNT_STATS: 'apiCountStats',           // API数量统计
    API_CATEGORY_STATS: 'apiCategoryStats',     // API分类统计
    API_VERSION_STATS: 'apiVersionStats',       // API版本统计
    API_STATUS_STATS: 'apiStatusStats',         // API状态统计
    API_CALL_STATS: 'apiCallStats',             // API调用统计
    API_RESPONSE_STATS: 'apiResponseStats',     // API响应统计
    API_DEPENDENCY_STATS: 'apiDependencyStats'  // API依赖关系统计
  },
  [MODULES.DATASET_MANAGEMENT]: {
    UPLOAD_DATASET: 'uploadDataset',
    DATASET_VERSIONING: 'datasetVersioning',
    DATA_VISUALIZATION: 'dataVisualization',
    DATA_TRANSFORMATION: 'dataTransformation'
  },
  [MODULES.LOWCODE_BUILDER]: {
    DB_CONNECTOR: 'dbConnector',
    VISUAL_BUILDER: 'visualBuilder',
    TEMPLATES: 'templates'
  },
  [MODULES.REVIEW_ORDERS]: {
    APPROVAL_WORKFLOW: 'approvalWorkflow',
    ORDER_MANAGEMENT: 'orderManagement',
    BILLING: 'billing',
    SUBSCRIPTION: 'subscription'
  },
  [MODULES.ANALYTICS]: {
    REVENUE_ANALYTICS: 'revenueAnalytics',
    BUSINESS_ANALYTICS: 'businessAnalytics',
    EXPORT_REPORTS: 'exportReports',
    CUSTOM_DASHBOARDS: 'customDashboards'
  },
  [MODULES.ADMIN]: {
    USER_MANAGEMENT: 'userManagement',
    ROLE_MANAGEMENT: 'roleManagement',
    PERMISSION_MANAGEMENT: 'permissionManagement',
    PERMISSION_ASSIGNMENT: 'permissionAssignment',
    PERMISSION_AUDIT: 'permissionAudit',
    PERMISSION_TEMPLATES: 'permissionTemplates',
    PERMISSION_ANALYTICS: 'permissionAnalytics',
    AUDIT_LOGS: 'auditLogs'
  }
};

// 市场配置 - 每个市场支持的模块和功能
const marketConfigurations = {
  // 中国市场 - 完整功能
  'china': {
    modules: [
      MODULES.API_MANAGEMENT,
      MODULES.DATASET_MANAGEMENT,
      MODULES.LOWCODE_BUILDER,
      MODULES.REVIEW_ORDERS,
      MODULES.ANALYTICS,
      MODULES.ADMIN
    ],
    features: {
      [MODULES.API_MANAGEMENT]: [
        FEATURES[MODULES.API_MANAGEMENT].CREATE_API,
        FEATURES[MODULES.API_MANAGEMENT].API_VERSIONING,
        FEATURES[MODULES.API_MANAGEMENT].API_DOCUMENTATION,
        FEATURES[MODULES.API_MANAGEMENT].API_MOCKING,
        FEATURES[MODULES.API_MANAGEMENT].API_TESTING,
        FEATURES[MODULES.API_MANAGEMENT].API_STATISTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_PERFORMANCE,
        FEATURES[MODULES.API_MANAGEMENT].API_USAGE_ANALYTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_ERROR_ANALYTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_COUNT_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_CATEGORY_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_VERSION_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_STATUS_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_CALL_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_RESPONSE_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_DEPENDENCY_STATS
      ],
      [MODULES.DATASET_MANAGEMENT]: [
        FEATURES[MODULES.DATASET_MANAGEMENT].UPLOAD_DATASET,
        FEATURES[MODULES.DATASET_MANAGEMENT].DATASET_VERSIONING,
        FEATURES[MODULES.DATASET_MANAGEMENT].DATA_VISUALIZATION,
        FEATURES[MODULES.DATASET_MANAGEMENT].DATA_TRANSFORMATION
      ],
      [MODULES.LOWCODE_BUILDER]: [
        FEATURES[MODULES.LOWCODE_BUILDER].DB_CONNECTOR,
        FEATURES[MODULES.LOWCODE_BUILDER].VISUAL_BUILDER,
        FEATURES[MODULES.LOWCODE_BUILDER].TEMPLATES
      ],
      [MODULES.REVIEW_ORDERS]: [
        FEATURES[MODULES.REVIEW_ORDERS].APPROVAL_WORKFLOW,
        FEATURES[MODULES.REVIEW_ORDERS].ORDER_MANAGEMENT,
        FEATURES[MODULES.REVIEW_ORDERS].BILLING,
        FEATURES[MODULES.REVIEW_ORDERS].SUBSCRIPTION
      ],
      [MODULES.ANALYTICS]: [
        FEATURES[MODULES.ANALYTICS].REVENUE_ANALYTICS,
        FEATURES[MODULES.ANALYTICS].BUSINESS_ANALYTICS,
        FEATURES[MODULES.ANALYTICS].EXPORT_REPORTS,
        FEATURES[MODULES.ANALYTICS].CUSTOM_DASHBOARDS
      ],
      [MODULES.ADMIN]: [
        FEATURES[MODULES.ADMIN].USER_MANAGEMENT,
        FEATURES[MODULES.ADMIN].ROLE_MANAGEMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_MANAGEMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_ASSIGNMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_AUDIT,
        FEATURES[MODULES.ADMIN].PERMISSION_TEMPLATES,
        FEATURES[MODULES.ADMIN].PERMISSION_ANALYTICS,
        FEATURES[MODULES.ADMIN].AUDIT_LOGS
      ]
    }
  },
  
  // 北美市场 - 无审核中心，简化的分析功能
  'north-america': {
    modules: [
      MODULES.API_MANAGEMENT,
      MODULES.DATASET_MANAGEMENT,
      MODULES.LOWCODE_BUILDER,
      MODULES.ANALYTICS,
      MODULES.ADMIN
    ],
    features: {
      [MODULES.API_MANAGEMENT]: [
        FEATURES[MODULES.API_MANAGEMENT].CREATE_API,
        FEATURES[MODULES.API_MANAGEMENT].API_VERSIONING,
        FEATURES[MODULES.API_MANAGEMENT].API_DOCUMENTATION,
        FEATURES[MODULES.API_MANAGEMENT].API_TESTING,
        FEATURES[MODULES.API_MANAGEMENT].API_STATISTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_PERFORMANCE,
        FEATURES[MODULES.API_MANAGEMENT].API_USAGE_ANALYTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_COUNT_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_CATEGORY_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_CALL_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_RESPONSE_STATS
      ],
      [MODULES.DATASET_MANAGEMENT]: [
        FEATURES[MODULES.DATASET_MANAGEMENT].UPLOAD_DATASET,
        FEATURES[MODULES.DATASET_MANAGEMENT].DATASET_VERSIONING,
        FEATURES[MODULES.DATASET_MANAGEMENT].DATA_VISUALIZATION
      ],
      [MODULES.LOWCODE_BUILDER]: [
        FEATURES[MODULES.LOWCODE_BUILDER].DB_CONNECTOR,
        FEATURES[MODULES.LOWCODE_BUILDER].VISUAL_BUILDER
      ],
      [MODULES.ANALYTICS]: [
        FEATURES[MODULES.ANALYTICS].REVENUE_ANALYTICS,
        FEATURES[MODULES.ANALYTICS].BUSINESS_ANALYTICS
      ],
      [MODULES.ADMIN]: [
        FEATURES[MODULES.ADMIN].USER_MANAGEMENT,
        FEATURES[MODULES.ADMIN].ROLE_MANAGEMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_MANAGEMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_ASSIGNMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_AUDIT,
        FEATURES[MODULES.ADMIN].AUDIT_LOGS
      ]
    }
  },
  
  // 欧洲市场 - 合规性更强，包含审核，无低代码构建器
  'europe': {
    modules: [
      MODULES.API_MANAGEMENT,
      MODULES.DATASET_MANAGEMENT,
      MODULES.REVIEW_ORDERS,
      MODULES.ANALYTICS,
      MODULES.ADMIN
    ],
    features: {
      [MODULES.API_MANAGEMENT]: [
        FEATURES[MODULES.API_MANAGEMENT].CREATE_API,
        FEATURES[MODULES.API_MANAGEMENT].API_VERSIONING,
        FEATURES[MODULES.API_MANAGEMENT].API_DOCUMENTATION,
        FEATURES[MODULES.API_MANAGEMENT].API_STATISTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_ERROR_ANALYTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_COUNT_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_CATEGORY_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_VERSION_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_STATUS_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_DEPENDENCY_STATS
      ],
      [MODULES.DATASET_MANAGEMENT]: [
        FEATURES[MODULES.DATASET_MANAGEMENT].UPLOAD_DATASET,
        FEATURES[MODULES.DATASET_MANAGEMENT].DATASET_VERSIONING,
        FEATURES[MODULES.DATASET_MANAGEMENT].DATA_TRANSFORMATION
      ],
      [MODULES.REVIEW_ORDERS]: [
        FEATURES[MODULES.REVIEW_ORDERS].APPROVAL_WORKFLOW,
        FEATURES[MODULES.REVIEW_ORDERS].ORDER_MANAGEMENT,
        FEATURES[MODULES.REVIEW_ORDERS].SUBSCRIPTION
      ],
      [MODULES.ANALYTICS]: [
        FEATURES[MODULES.ANALYTICS].REVENUE_ANALYTICS,
        FEATURES[MODULES.ANALYTICS].BUSINESS_ANALYTICS,
        FEATURES[MODULES.ANALYTICS].EXPORT_REPORTS
      ],
      [MODULES.ADMIN]: [
        FEATURES[MODULES.ADMIN].USER_MANAGEMENT,
        FEATURES[MODULES.ADMIN].ROLE_MANAGEMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_MANAGEMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_ASSIGNMENT,
        FEATURES[MODULES.ADMIN].PERMISSION_AUDIT,
        FEATURES[MODULES.ADMIN].PERMISSION_TEMPLATES,
        FEATURES[MODULES.ADMIN].AUDIT_LOGS
      ]
    }
  },
  
  // 东南亚市场 - 简化版本，无管理员模块
  'southeast-asia': {
    modules: [
      MODULES.API_MANAGEMENT,
      MODULES.DATASET_MANAGEMENT,
      MODULES.REVIEW_ORDERS,
      MODULES.ANALYTICS
    ],
    features: {
      [MODULES.API_MANAGEMENT]: [
        FEATURES[MODULES.API_MANAGEMENT].CREATE_API,
        FEATURES[MODULES.API_MANAGEMENT].API_DOCUMENTATION,
        FEATURES[MODULES.API_MANAGEMENT].API_STATISTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_USAGE_ANALYTICS,
        FEATURES[MODULES.API_MANAGEMENT].API_COUNT_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_CATEGORY_STATS,
        FEATURES[MODULES.API_MANAGEMENT].API_CALL_STATS
      ],
      [MODULES.DATASET_MANAGEMENT]: [
        FEATURES[MODULES.DATASET_MANAGEMENT].UPLOAD_DATASET,
        FEATURES[MODULES.DATASET_MANAGEMENT].DATA_VISUALIZATION
      ],
      [MODULES.REVIEW_ORDERS]: [
        FEATURES[MODULES.REVIEW_ORDERS].ORDER_MANAGEMENT,
        FEATURES[MODULES.REVIEW_ORDERS].SUBSCRIPTION
      ],
      [MODULES.ANALYTICS]: [
        FEATURES[MODULES.ANALYTICS].REVENUE_ANALYTICS,
        FEATURES[MODULES.ANALYTICS].BUSINESS_ANALYTICS
      ]
    }
  }
};

export default marketConfigurations; 